<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <AssemblyName>BarterItemsStacksFika</AssemblyName>
    <RootNamespace>BarterItemsStacksFika</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <SPTRefDir>../../../../deps</SPTRefDir>

    <AssemblySearchPaths>
      $(SPTRefDir)/core;
      $(SPTRefDir)/plugins/spt;
      $(SPTRefDir)/managed;
      $(AssemblySearchPaths);
    </AssemblySearchPaths>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony" />
    <Reference Include="BepInEx" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="spt-reflection" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp" />
    <Reference Include="Comfort" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="UnityEngine" />
    <Reference Include="Fika.Core">
      <HintPath>$(SPTRefDir)/Fika.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="@(Reference)">
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyToBuildFolder" AfterTargets="Build">
    <PropertyGroup>
      <DestDir>$(MSBuildProjectDirectory)\..\..\build\BepInEx\plugins\</DestDir>
    </PropertyGroup>
    <MakeDir Directories="$(DestDir)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DestDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
